import random

# List of 100 different fortunes
fortunes = [
    "You will have a great day!",
    "Something unexpected will bring you joy!",
    "You will meet someone special soon.",
    "A pleasant surprise is waiting for you.",
    "Today is your lucky day!",
    "You will achieve your goals soon.",
    "A new opportunity will come your way.",
    "You will receive good news today.",
    "Happiness is around the corner.",
    "Your hard work will pay off.",
    "You will find the answer you are looking for.",
    "You will have a productive day.",
    "You will make a new friend.",
    "You will enjoy good health.",
    "Success is in your future.",
    "You will experience a positive change.",
    "You will have a relaxing day.",
    "An exciting adventure awaits you.",
    "You will receive a compliment today.",
    "You will overcome a challenge.",
    "You will have a moment of clarity.",
    "You will find something you lost.",
    "You will receive help from an unexpected source.",
    "You will have a creative idea.",
    "You will discover a hidden talent.",
    "You will enjoy a pleasant conversation.",
    "You will have a reason to celebrate.",
    "You will make someone smile.",
    "You will have a moment of peace.",
    "You will achieve a personal goal.",
    "You will receive a pleasant surprise.",
    "You will feel inspired today.",
    "You will have a lucky break.",
    "You will find joy in simple things.",
    "You will receive a kind gesture.",
    "You will have a fun day.",
    "You will learn something new.",
    "You will have a moment of reflection.",
    "You will have a productive conversation.",
    "You will find a solution to a problem.",
    "You will enjoy a pleasant experience.",
    "You will receive praise for your efforts.",
    "You will have a moment of success.",
    "You will make a positive impact.",
    "You will feel appreciated.",
    "You will receive good advice.",
    "You will enjoy a moment of tranquility.",
    "You will find inspiration in nature.",
    "You will have a moment of laughter.",
    "You will enjoy a special treat.",
    "You will have a fulfilling day.",
    "You will receive a pleasant memory.",
    "You will feel a sense of accomplishment.",
    "You will have a moment of kindness.",
    "You will experience a joyful moment.",
    "You will feel a sense of peace.",
    "You will have a productive week.",
    "You will enjoy good fortune.",
    "You will feel motivated.",
    "You will have a moment of clarity.",
    "You will receive a thoughtful gift.",
    "You will enjoy a moment of relaxation.",
    "You will have a positive outlook.",
    "You will feel a sense of pride.",
    "You will experience a moment of gratitude.",
    "You will have a memorable day.",
    "You will feel a sense of joy.",
    "You will achieve a significant milestone.",
    "You will feel a sense of relief.",
    "You will enjoy a pleasant surprise.",
    "You will find joy in helping others.",
    "You will have a successful day.",
    "You will feel a sense of satisfaction.",
    "You will experience a moment of wonder.",
    "You will receive a compliment.",
    "You will feel a sense of calm.",
    "You will have a moment of happiness.",
    "You will achieve a goal.",
    "You will enjoy a moment of peace.",
    "You will feel a sense of accomplishment.",
    "You will receive good news.",
    "You will find joy in your work.",
    "You will have a productive day.",
    "You will experience a moment of clarity.",
    "You will receive a pleasant surprise.",
    "You will feel a sense of fulfillment.",
    "You will enjoy a moment of laughter.",
    "You will feel a sense of joy.",
    "You will receive a kind gesture.",
    "You will have a moment of tranquility.",
    "You will experience a joyful moment.",
    "You will feel a sense of peace.",
    "You will have a productive week.",
    "You will enjoy good fortune.",
    "You will feel motivated.",
    "You will have a moment of clarity.",
    "You will receive a thoughtful gift."
]

# Generate a random lucky number and a random fortune number
lucky_number = random.randint(1, 100)
fortune_number = random.randint(1, 100)

# Select the fortune text based on the fortune number
fortune_text = fortunes[fortune_number - 1]

print(f'{fortune_text} Your lucky number is: {lucky_number}')
